Sprint 10
NekhoroshkinaElena/java-filmorate pull request #2
Opened 2022-08-17 07:26 UTC by NekhoroshkinaElena

feat: создать новые интерфейсы FilmStorage и UserStorage в которых определены методы добавления, удаления и модификации объектов

refactor: создать новые классы InMemoryFilmStorage и InMemoryUserStorage в которые перенесена логика хранения, обновления и поиска объектов.

feat: создать классы UserService и FilmService с новой функциональностью

feat: создать класс ErrorHandler для централизованной обработки ошибок

2022-08-17 19:53 UTC, chewmag reviewed
Приветствую Елена!

Критичных замечаний в работе нет. Предлагаю подумать над возможностью доработок:

- сделать ValidateException непроверяемым;
- убрать декларацию UserNotFoundException с методов;
- убрать @Slf4j там, где он по факту не используется;
- возможно добавить javadocs в интерфейсы FilmStorage, UserStorage.

2022-08-17 19:53 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Slf4j
По всей видимости логгер тут больше не нужен :)

2022-08-17 19:53 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getTop10Films(int count) {
Название метода сужает его гибкость: все-таки количество фильмов настраивается через аргумент.

2022-08-17 19:53 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/exeption/ValidationException.java
>  public class ValidationException extends Exception {
Не очень понятно, зачем ValidateException делать проверяемым, мы же это нигде не обрабатываем кроме ErrorHandler'a, которому все равно, проверяемое или непроверяемое исключение ловить.

2022-08-17 19:53 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void addFriend(long id, long friendId) throws UserNotFoundException {
Здесь и ниже нет необходимости декларировать UserNotFoundException

2022-08-18 07:40 UTC, NekhoroshkinaElena commented
Замечания исправлены, возможно, неправильно оформила документацию, так как не знаю всех требований к оформлению :(

2022-08-18 19:57 UTC, chewmag requested changes
Приветствую Елена!

Предлагаю улучшить дизайн использования сервисов: лучше вынести все необходимые методы в сервисы (работы со storage), чтобы вся сервисная часть была в них. В итоге в отдельно взятом контроллере все вызовы должны пойти в один сервис, а не в два, как сейчас.

2022-08-18 19:57 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return inMemoryFilmStorage.getAllFilms();
Обычно все работу с хранилищем делегируют сервису, то есть было бы лучше сделать в FilmService соотвествующий метод, а уже внутри него использовать FilmStorage.

2022-08-18 19:57 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> + * Интерфейс для хранилища фильмов
Документация хорошая, только предложения над методами лучше с большой буквы и в конце ставить точку.

2022-08-19 09:41 UTC, NekhoroshkinaElena commented
Добрый день:) Постаралась исправить все недочёты.

2022-08-19 17:51 UTC, chewmag approved these changes
Здравствуйте Елена!

Теперь полный порядок, спасибо за улучшения и рефакторинг :)

2022-08-25 05:20 UTC, merged