initial commit
NekhoroshkinaElena/java-filmorate pull request #3
Opened 2022-09-15 13:46 UTC by NekhoroshkinaElena

проверить прохождение тестов

2022-09-16 12:19 UTC, NekhoroshkinaElena commented
Добрый день, добавила в приложение новую функциональность, очень жду вашей оценки:)

2022-09-17 12:12 UTC, chewmag requested changes
Приветствую Елена!

По заданию требовалось добавить новые имплементации к интерфейсам FilmStorage, UserStorage, но хранение в памяти кануло в лету ) Отсюда бы потребовалось использовать @Qualifier, чтобы подключить нужную имплементацию. Еще один момент, который нужно исправить: при получении фильмов в методе FilmDbStorage:getFilmById нужно собрать жанры из уже выполненного запроса, а не делать отдельный новый.

2022-09-17 12:12 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                Film film = new Film(
В этом же классе есть метод makeFilm, он как раз создает Film из ResultSet'a

2022-09-17 12:12 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +        getUniqueID();
А почему не передать getUniqueID в user.setId ?

2022-09-18 10:11 UTC, NekhoroshkinaElena commented
Добрый день, постаралась исправить указанные ошибки. Очень долго не могла разобраться с ошибкой: "В методе FilmDbStorage:getFilmById нужно собрать жанры из уже выполненного запроса, а не делать отдельный новый." Надеюсь, что правильно вас поняла:)

2022-09-18 17:41 UTC, chewmag approved these changes
Приветствую Елена!

Улучшения в FilmDbStorage реализованы, можно мерджить PR в main 👍

2022-09-18 17:41 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +                "WHERE (f.user_id = ? OR f.user_id = ?) AND (f.friend_id != ? AND f.friend_id != ?)";
достаточно один раз f.user_id = ?  и f.friend_id != ? , в таком виде это дублирование )

2022-09-19 18:15 UTC, NekhoroshkinaElena commented
убрала прямое дублирование кода

2022-09-19 18:15 UTC, merged